version: 2
jobs:
  build:
    docker:
      - image: node:10
    working_directory: ~/repo

    steps:
      - checkout
      - run: yarn --version

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-

      - run: yarn install --frozen-lockfile
      - run: yarn bootstrap
      - run: yarn build
      - run: yarn test

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
