version: 2
aliases:
  - &restore-cache
    keys:
      - v1-dependencies-{{ .Branch }}-{{ checksum "package.json" }}
      - v1-dependencies-{{ .Branch }}

  - &save-node-cache
    key: v1-dependencies-{{ .Branch }}-{{ checksum "package.json" }}
    paths:
      - node_modules

  - &install-node-dependencies
    name: Install node dependencies
    command: yarn install --frozen-lockfile

  - &bootstrap-packages
    name: Bootstrap packages
    command: yarn bootstrap

  - &build-packages
    name: Build packages
    command: yarn build

defaults: &defaults
  working_directory: ~/daf

jobs:
  test-packages:
    <<: *defaults
    docker:
      - image: node:10
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run: *install-node-dependencies
      - run: *bootstrap-packages
      - run: *build-packages
      - save_cache: *save-node-cache
      - run: yarn test --maxWorkers 2

  publish-packages-npm:
    <<: *defaults
    docker:
      - image: node:10
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run: *install-node-dependencies
      - run: *bootstrap-packages
      - run: *build-packages
      - run:
          name: Set git user
          command: |
            git remote set-url origin https://uport-project:$GITHUB_TOKEN@github.com/uport-project/daf.git
            git config --global user.email $GITHUB_EMAIL
            git config --global user.name $GITHUB_USER
            npm set unsafe-perm true -g
            npm set //registry.npmjs.org/:_authToken $NPM_TOKEN -g
            npm set username $NPM_USERNAME -g
            npm set email $NPM_EMAIL -g
      - run:
          name: Release packages to npm
          command: npx lerna publish --yes

workflows:
  version: 2

  verify-test-build:
    jobs:
      - test-packages
      - publish-packages-npm:
          filters:
            branches:
              only:
                - master
          requires:
            - test-packages
